#!/bin/bash

set -e

RED='\e[1;31m'
GREEN='\e[1;32m'
RESET_COLOR='\033[0m'

export COUNTRY
export PROVINCE
export LOCALITY
export ORGANIZATION
export UNIT
export DOMAIN
export DAYS

clean-confs() {
[ -x ./scripts/clean-values ] && ./scripts/clean-values $RESET_COLOR && exit 0
}

clean-database() {
[ -x ./scripts/clean-database ] && ./scripts/clean-database $RESET_COLOR && exit 0
}

clean-files() {
[ -x ./scripts/clean-files ] && ./scripts/clean-files $RESET_COLOR && exit 0
}

root() {
ROOTCA=OK
[ -x ./scripts/rootca ] && ./scripts/rootca $RESET_COLOR && exit 0
}

intermediate() {
INTERMEDIATECA=OK
if [ ! -e out/ca/certs/rootca.crt ] && [ ! -e out/ca/keys/rootca.key ]; then
        echo -e $RED "You must first create a certificate for the root authority." $RESET_COLOR
        exit 1
fi

[ -x ./scripts/intca ] && ./scripts/intca $RESET_COLOR && exit 0
}

server() {
SERVERCERT=OK
[ -x ./scripts/clean-values ] && ./scripts/clean-values $RESET_COLOR
if [ ! -e out/ca/certs/intca.crt ] && [ ! -e out/ca/keys/intca.key ]; then
        echo -e $RED "You must first create a certificate for the root authority and the intermediate autority." $RESET_COLOR
        exit 1
fi

[ -x ./scripts/servercert ] && ./scripts/servercert $RESET_COLOR && exit 0
}

client() {
CLIENTCERT=OK
[ -x ./scripts/clean-values ] && ./scripts/clean-values $RESET_COLOR
if [ ! -e out/ca/certs/intca.crt ] && [ ! -e out/ca/keys/intca.key ]; then
        echo -e $RED "You must first create a certificate for the root authority and the intermediate autority." $RESET_COLOR
        exit 1
fi

[ -x ./scripts/clientcert ] && ./scripts/clientcert $RESET_COLOR && exit 0
}

diffie-hellman() {
DH=1
openssl dhparam -out ./out/dhparams.pem 4096
}

ARGS=$(getopt -o hcbfr:i:s:t:en:p:l:o:u:m:d: -l help,clean-confs,clean-database,clean-files,root:,intermediate:,server:,client:,diffie-hellman,country:,province:,locality:,organization:,unit:,domain:,days: -- "$@")
eval set -- "$ARGS"
while true
do
        case "$1" in
                -h|--help) help; ;;
                -c|--clean-confs) clean-confs; ;;
		-b|--clean-database) clean-database; ;;
		-f|--clean-files) clean-files; ;;
		-r|--root) root; ;;
                -i|--intermediate) intermediate; ;;
		-s|--server) server; ;;
		-t|--client) client; ;;
		-e|--diffie-hellman) diffie-hellman; ;;
                -n|--country) COUNTRY=$2; shift 2; ;;
                -p|--province) PROVINCE=$2; shift 2; ;;
		-l|--locality) LOCALITY=$2; shift 2; ;;
		-o|--organization) ORGANIZATION=$2; shift 2; ;;
		-u|--unit) UNIT=$2; shift 2; ;;
		-m|--domain) DOMAIN=$2; shift 2; ;;
		-d|--days) DAYS=$2; shift 2; ;;
                --) shift; break; ;;
                 *) echo -e $RED "Internal error, unhandled option: $1"; exit 1; ;;
        esac
done

if [ -z "$COUNTRY" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the country name." $RESET_COLOR
	exit 1
fi

if [[ "$COUNTRY" != [A-Z][A-Z] ]] && [ -z "$DH" ]; then
	echo -e $RED "The name of the country may not contain any characters other than two capital letters." $RESET_COLOR
	exit 1
fi

if [ -z "$PROVINCE" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the state or the province name." $RESET_COLOR
	exit 1
fi

if [ -z "$LOCALITY" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the name of the locality." $RESET_COLOR
	exit 1
fi

if [ -z "$ORGANIZATION" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the name of your organization." $RESET_COLOR
	exit 1
fi

if [ -z "$UNIT" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the name of your organizational unit." $RESET_COLOR
	exit 1
fi

if [ -z "$DOMAIN" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the common name (FQDN or hostname)." $RESET_COLOR
	exit 1
fi

if [ -z "$DAYS" ] && [ -z "$DH" ]; then
	echo -e $RED "Define a value for the duration of your certification autority or your server cert." $RESET_COLOR
	exit 1
fi

if [[ "$DAYS" != [0-9][0-9]?? ]] && [ -z "$DH" ]; then
	echo -e $RED "The number of the certificate validity may not contain any characters other than two, three or four numbers." $RESET_COLOR
	exit 1
fi

if [ -z "$ROOTCA" ] && [ -z "$INTERMEDIATECA" ] && [ -z "$SERVERCERT" ] && [ -z "$CLIENTCERT" ] && [ -z "$DH" ]; then
	echo -e $RED "You must define whether it's a root, intermediate authority or a server certificate." $RESET_COLOR
	exit 1
fi
