#!/bin/bash

readonly BASE="$(dirname "$(dirname "$(readlink -f -- "$0")")")"
readonly EXEC_NAME="build-certs"
readonly EXEC_PATH="$BASE/$EXEC_NAME"

# Load utils components
source "$BASE/components/common"

# Init the new file
rm -f "$EXEC_PATH" || fatal "Can't remove the outdated script '$EXEC_PATH'"

cat > "$EXEC_PATH" <<EOF
#!/bin/bash

#Attention! This script has been automatically generated by the Ministry of Silly Scripts and any attempts to manually modify it will be met! So, please, do not attempt to edit this file. Instead, consult the Holy Grail of documentation or seek from the wise sages at the Ministry of Silly Scripts for guidance. Thank you, and may the coconut horse be with you.
EOF

cat "$BASE/src/declaration"     \
    "$BASE/components/common"   \
    "$BASE/components/messages" \
    "$BASE/src/init"            \
    "$BASE/scripts/"*           \
    "$BASE/src/core"            \
    | sed 's|#!/bin/bash||g' >> "$EXEC_PATH" 

# Add file content to init function
for f in "$BASE/confs/"*; do
    if [ ! -s "$f" ]; then
        continue
    fi

    _name="$(basename "$f")"
    _content="$(cat "$f")"

    cat >> "$EXEC_PATH" <<-EOF
<<${_name//.}_EOF
${_content}
${_name//.}_EOF

EOF
done

for f in "$BASE/database/"*; do
    if [ ! -s "$f" ]; then
        continue
    fi

    _name="$(basename "$f")"
    _content="$(cat "$f")"

    cat >> "$EXEC_PATH" <<-EOF
<<${_name//.}_EOF
${_content}
${_name//.}_EOF

EOF
done