#!/bin/bash

clean-files() {
    rm -f "$CACRT/"*
    rm -f "$CACSR/"*
    rm -f "$CAKEY/"*
    rm -f "$CAKEY/."[^.key]*
    rm -f "$SRVCRT"/*
    rm -f "$SRVCSR"/*
    rm -f "$SRVKEY"/*
    rm -f "$SRVKEY"/.[^.key]*
}
