#!/bin/bash

clean-database() {
    rm -f                           \
    "$DATABASE/certindex.attr.old"* \
    "$DATABASE/certindex.old"*      \
    "$DATABASE/certserial.old"*     \
    "$DATABASE/certindex"           \
    "$DATABASE/crlnumber"*

    touch "$DATABASE/certindex" "$DATABASE/crlnumber"
    echo 1000 > "$DATABASE/certserial"
}
