#!/bin/bash

clean-confs() {
    sed -i "s/C = .*/C =/g" "$CFG/server.cnf"
    sed -i "s/ST = .*/ST =/g" "$CFG/server.cnf"
    sed -i "s/L = .*/L =/g" "$CFG/server.cnf"
    sed -i "s/O = .*/O =/g" "$CFG/server.cnf"
    sed -i "s/OU = .*/OU =/g" "$CFG/server.cnf"
    sed -i "s/CN = .*/CN =/g" "$CFG/server.cnf"
    sed -i "s/DNS.1 = .*/DNS.1 =/g" "$CFG/server.cnf"
    sed -i "s/C = .*/C =/g" "$CFG/ca.cnf"
    sed -i "s/ST = .*/ST =/g" "$CFG/ca.cnf"
    sed -i "s/L = .*/L =/g" "$CFG/ca.cnf"
    sed -i "s/O = .*/O =/g" "$CFG/ca.cnf"
    sed -i "s/OU = .*/OU =/g" "$CFG/ca.cnf"
    sed -i "s/CN = .*/CN =/g" "$CFG/ca.cnf"
}
