#!/bin/bash

set -e

sed -i "s/C = .*/C =/g" confs/ca.cnf
sed -i "s/ST = .*/ST =/g" confs/ca.cnf
sed -i "s/L = .*/L =/g" confs/ca.cnf
sed -i "s/O = .*/O =/g" confs/ca.cnf
sed -i "s/OU = .*/OU =/g" confs/ca.cnf
sed -i "s/CN = .*/CN =/g" confs/ca.cnf
sed -i "s/C =/C = $COUNTRY/g" confs/ca.cnf
sed -i "s/ST =/ST = $PROVINCE/g" confs/ca.cnf
sed -i "s/L =/L = $LOCALITY/g" confs/ca.cnf
sed -i "s/O =/O = $ORGANIZATION/g" confs/ca.cnf
sed -i "s/OU =/OU = $UNIT/g" confs/ca.cnf
sed -i "s/CN =/CN = $DOMAIN/g" confs/ca.cnf

#Generate the private key
openssl genrsa -out cakey/intca.key 4096
#Generate the CSR
openssl req -sha512 -new -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -key cakey/intca.key -out cacsr/intca.csr
#Generate the intermediate certificate
openssl ca -batch -config confs/ca.cnf -days $DAYS -extensions v3_ca -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -notext -in cacsr/intca.csr -out cacerts/intca.crt
