#!/bin/bash

set -e

sed -i "s/C = .*/C =/g" confs/ca.cnf
sed -i "s/ST = .*/ST =/g" confs/ca.cnf
sed -i "s/L = .*/L =/g" confs/ca.cnf
sed -i "s/O = .*/O =/g" confs/ca.cnf
sed -i "s/OU = .*/OU =/g" confs/ca.cnf
sed -i "s/CN = .*/CN =/g" confs/ca.cnf
sed -i "s/C =/C = $COUNTRY/g" confs/ca.cnf
sed -i "s/ST =/ST = $PROVINCE/g" confs/ca.cnf
sed -i "s/L =/L = $LOCALITY/g" confs/ca.cnf
sed -i "s/O =/O = $ORGANIZATION/g" confs/ca.cnf
sed -i "s/OU =/OU = $UNIT/g" confs/ca.cnf
sed -i "s/CN =/CN = $DOMAIN/g" confs/ca.cnf

#Create the autosigned the root autority certificate
openssl req -x509 -nodes -newkey rsa:4096 -days $DAYS -extensions v3_ca -subj "/C=$COUNTRY/ST=$PROVINCE/O=$ORGANIZATION/OU=$UNIT/L=$LOCALITY/CN=$DOMAIN" -keyout out/ca/keys/rootca.key -out out/ca/certs/rootca.crt -config confs/ca.cnf
