#!/bin/bash

set -e

sed -i "s/C = .*/C =/g" confs/server.cnf
sed -i "s/ST = .*/ST =/g" confs/server.cnf
sed -i "s/L = .*/L =/g" confs/server.cnf
sed -i "s/O = .*/O =/g" confs/server.cnf
sed -i "s/OU = .*/OU =/g" confs/server.cnf
sed -i "s/CN = .*/CN =/g" confs/server.cnf
sed -i "s/DNS.1 = .*/DNS.1 =/g" confs/server.cnf
sed -i "s/C =/C = $COUNTRY/g" confs/server.cnf
sed -i "s/ST =/ST = $PROVINCE/g" confs/server.cnf
sed -i "s/L =/L = $LOCALITY/g" confs/server.cnf
sed -i "s/O =/O = $ORGANIZATION/g" confs/server.cnf
sed -i "s/OU =/OU = $UNIT/g" confs/server.cnf
sed -i "s/CN =/CN = $DOMAIN/g" confs/server.cnf
sed -i "s/DNS.1 =/DNS.1 = $DOMAIN/g" confs/server.cnf

#Create a private key for the server cert
openssl genrsa -out out/server/keys/"$DOMAIN".key 4096
#Create a CSR with the intermediate autority certificate
openssl req -new -key out/server/keys/"$DOMAIN".key -out out/server/csr/"$DOMAIN".csr -config confs/server.cnf
#Sign the CSR with the intermediate autority certificate
openssl x509 -req -in out/server/csr/"$DOMAIN".csr -CA out/ca/certs/intca.crt -CAkey out/ca/keys/intca.key -CAcreateserial -out out/server/certs/"$DOMAIN".crt -days $DAYS -sha512 -extfile confs/server.cnf
